import DocLayout from "@/features/docs/components/layout/doc-layout";
import MarkdownRenderer from "@/features/docs/components/markdown/md-rendorer";
import DocsPagination from "@/features/docs/components/navigation/doc-pagination";

const content = `
# Quick Start

Let's create a simple **Product API**.

You don't need to build a backend or create a database table.

## 1. Create a project

Open the Mokvio dashboard.

Create a new project.

For example:

\`\`\`text
Ecommerce
\`\`\`

Click **Create**.

## 2. Create a resource

Open your new project.

Create a resource named:

\`\`\`text
Product
\`\`\`

Your project now looks like:

\`\`\`text
Ecommerce
└── Product
\`\`\`

## 3. Add fields

Open the Product resource and add some fields.

For example:

| Field | Type | Generator |
| --- | --- | --- |
| name | String | Full Name |
| price | Decimal | Price |
| stock | Integer | Integer |
| image | String | Image URL |

You can choose different generators depending on the data you need.

## 4. Publish your resource

When your fields are ready, publish the resource.

Mokvio will make the resource available through its mock API.

## 5. Copy the API URL

Open the runtime/API section of your resource.

You will see your generated API URL.

Copy it.

It will look similar to:

\`\`\`text
https://your-mockvio-url/api/ecommerce/product
\`\`\`

Your actual URL will depend on your project and resource.

## 6. Open the API

Paste the URL into your browser.

You should receive generated JSON.

For example:

\`\`\`json
{
  "name": "John Smith",
  "price": 2499.99,
  "stock": 42,
  "image": "https://example.com/image.jpg"
}
\`\`\`

The values will be generated by Mokvio and can be different each time.

## 7. Use it in your application

Now you can use the URL in your application.

For example, with JavaScript:

\`\`\`javascript
const response = await fetch(
  "https://your-mockvio-url/api/ecommerce/product"
);

const data = await response.json();
\`\`\`

You can also use Axios or any other HTTP client.

That's it.

You now have a working mock API.

## The whole process

\`\`\`text
Create Project
      ↓
Create Resource
      ↓
Add Fields
      ↓
Choose Generators
      ↓
Publish
      ↓
Copy API URL
      ↓
Use it in your application
\`\`\`

## What can you do next?

Now that you know the basic workflow, continue with:

- **Projects & Resources** to understand how your API is organized.
- **Fields** to learn about field configuration.
- **Data Generators** to see the available ways to generate data.
- **Example to connect API** to use your Mokvio API in a frontend application.
`;

function QuickStart() {
  return (
    <DocLayout>
      <div className="mx-auto w-full max-w-4xl px-6 py-10">
        <MarkdownRenderer>{content}</MarkdownRenderer>

        <DocsPagination />
      </div>
    </DocLayout>
  );
}

export default QuickStart;
