# Generated by Django 6.1 on 2026-08-12 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projects",
            name="slug",
            field=models.SlugField(max_length=100),
        ),
    ]
