# Generated by Django 6.1 on 2026-08-13 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_alter_projects_slug"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="projects",
            new_name="project_owner_updated_idx",
            old_name="projects_pr_owner_i_735188_idx",
        ),
        migrations.RenameIndex(
            model_name="projects",
            new_name="project_slug_published_idx",
            old_name="projects_pr_slug_c5240c_idx",
        ),
        migrations.AlterField(
            model_name="projects",
            name="is_published",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Whether this project is publicly available through its mock API.",
            ),
        ),
        migrations.AlterField(
            model_name="projects",
            name="name",
            field=models.CharField(
                help_text="Human-readable name of the project.", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="projects",
            name="owner",
            field=models.ForeignKey(
                help_text="User who owns this project.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="projects",
            name="slug",
            field=models.SlugField(
                help_text="URL-safe identifier unique within the owner's projects.",
                max_length=100,
            ),
        ),
    ]
