# Generated by Django 6.1 on 2026-08-13 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_bio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="user",
            name="deleted_by",
        ),
        migrations.RemoveField(
            model_name="user",
            name="failed_login_attempts",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_suspended",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_login_ip",
        ),
        migrations.RemoveField(
            model_name="user",
            name="locked_until",
        ),
        migrations.RemoveField(
            model_name="user",
            name="suspended_at",
        ),
        migrations.RemoveField(
            model_name="user",
            name="suspension_reason",
        ),
    ]
