import DocLayout from "@/features/docs/components/layout/doc-layout";
import MarkdownRenderer from "@/features/docs/components/markdown/md-rendorer";
import DocsPagination from "@/features/docs/components/navigation/doc-pagination";

const content = `
# Connect MockForge to Your Application

Once you have created and published a resource, you can use the generated API in your application.

MockForge provides a normal HTTP API, so you can connect it using **Fetch**, **Axios**, or any other HTTP client.

## Get your API URL

Open your published resource in the MockForge dashboard.

Copy the generated API URL.

It will look similar to:

\`\`\`text
https://your-mockforge-url/api/ecommerce/products
\`\`\`

Your actual URL will depend on your MockForge project and resource.

## Test the API first

Before connecting it to your application, open the API URL in your browser.

You should receive generated JSON data.

For example:

\`\`\`json
[
  {
    "id": 1,
    "name": "John Smith",
    "price": 2499.99,
    "stock": 42
  },
  {
    "id": 2,
    "name": "Sarah Johnson",
    "price": 1599.5,
    "stock": 18
  }
]
\`\`\`

The values are generated by MockForge.

## Use MockForge with JavaScript

You can use the browser's built-in **fetch** function.

\`\`\`javascript
const response = await fetch(
  "https://your-mockforge-url/api/ecommerce/products"
);

const products = await response.json();

console.log(products);
\`\`\`

That's all you need to make a request.

## Use MockForge with React

You can request the API from a React application.

For example:

\`\`\`javascript
import { useEffect, useState } from "react";

function Products() {
  const [products, setProducts] = useState([]);

  useEffect(() => {
    fetch("https://your-mockforge-url/api/ecommerce/products")
      .then((response) => response.json())
      .then((data) => setProducts(data));
  }, []);

  return (
    <div>
      {products.map((product) => (
        <div key={product.id}>
          {product.name}
        </div>
      ))}
    </div>
  );
}
\`\`\`

You can now build your UI using the mock data.

## Use MockForge with Axios

If your application already uses Axios, you can use the generated API directly.

\`\`\`javascript
import axios from "axios";

const response = await axios.get(
  "https://your-mockforge-url/api/ecommerce/products"
);

console.log(response.data);
\`\`\`

You do not need a special MockForge package.

## Use MockForge with any frontend

MockForge works with applications that can make HTTP requests.

For example:

- React
- Vue
- Angular
- React Native
- Flutter
- Vanilla JavaScript
- Mobile applications
- Postman
- Insomnia

The important part is simply the generated API URL.

## Using the API during development

A common workflow is:

\`\`\`text
Your Application
      ↓
MockForge API
      ↓
Generated JSON
\`\`\`

You can build your frontend using MockForge while the real backend is still being developed.

Later, you can replace the MockForge URL with your real API URL.

For example:

\`\`\`text
Development:

https://mockforge.example/api/products

Production:

https://api.example.com/products
\`\`\`

Your frontend can keep the same general data structure while the backend changes.

## Important

Make sure the resource is **published** before trying to use its mock API.

If the endpoint does not work:

1. Check that the project exists.
2. Check that the resource exists.
3. Check that the resource is published.
4. Check that you copied the correct API URL.
5. Try opening the URL directly in your browser.

## What's next?

You can now use MockForge as the API for your frontend during development.

Continue with **API Reference** if you want to learn more about the available API endpoints.
`;

function ConnectMockForge() {
  return (
    <DocLayout>
      <div className="mx-auto w-full max-w-4xl px-6 py-10">
        <MarkdownRenderer>{content}</MarkdownRenderer>
        <DocsPagination />
      </div>
    </DocLayout>
  );
}

export default ConnectMockForge;
