import DocLayout from "@/features/docs/components/layout/doc-layout";
import MarkdownRenderer from "@/features/docs/components/markdown/md-rendorer";
import DocsPagination from "@/features/docs/components/navigation/doc-pagination";

const content = `
# Connect Mokvio to Your Application

Once you have created and published a resource, you can use the generated API in your application.

Mokvio provides a normal HTTP API, so you can connect it using **Fetch**, **Axios**, or any other HTTP client.

## Get your API URL

Open your published resource in the Mokvio dashboard.

Copy the generated API URL.

It will look similar to:

\`\`\`text
https://your-mokvio-url/api/ecommerce/products
\`\`\`

Your actual URL will depend on your Mokvio project and resource.

## Test the API first

Before connecting it to your application, open the API URL in your browser.

You should receive generated JSON data.

For example:

\`\`\`json
[
  {
    "id": 1,
    "name": "John Smith",
    "price": 2499.99,
    "stock": 42
  },
  {
    "id": 2,
    "name": "Sarah Johnson",
    "price": 1599.5,
    "stock": 18
  }
]
\`\`\`

The values are generated by Mokvio.

## Use Mokvio with JavaScript

You can use the browser's built-in **fetch** function.

\`\`\`javascript
const response = await fetch(
  "https://your-mokvio-url/api/ecommerce/products"
);

const products = await response.json();

console.log(products);
\`\`\`

That's all you need to make a request.

## Use Mokvio with React

You can request the API from a React application.

For example:

\`\`\`javascript
import { useEffect, useState } from "react";

function Products() {
  const [products, setProducts] = useState([]);

  useEffect(() => {
    fetch("https://your-mokvio-url/api/ecommerce/products")
      .then((response) => response.json())
      .then((data) => setProducts(data));
  }, []);

  return (
    <div>
      {products.map((product) => (
        <div key={product.id}>
          {product.name}
        </div>
      ))}
    </div>
  );
}
\`\`\`

You can now build your UI using the mock data.

## Use Mokvio with Axios

If your application already uses Axios, you can use the generated API directly.

\`\`\`javascript
import axios from "axios";

const response = await axios.get(
  "https://your-mokvio-url/api/ecommerce/products"
);

console.log(response.data);
\`\`\`

You do not need a special Mokvio package.

## Use Mokvio with any frontend

Mokvio works with applications that can make HTTP requests.

For example:

- React
- Vue
- Angular
- React Native
- Flutter
- Vanilla JavaScript
- Mobile applications
- Postman
- Insomnia

The important part is simply the generated API URL.

## Using the API during development

A common workflow is:

\`\`\`text
Your Application
      ↓
Mokvio API
      ↓
Generated JSON
\`\`\`

You can build your frontend using Mokvio while the real backend is still being developed.

Later, you can replace the Mokvio URL with your real API URL.

For example:

\`\`\`text
Development:

https://mokvio.example/api/products

Production:

https://api.example.com/products
\`\`\`

Your frontend can keep the same general data structure while the backend changes.

## Important

Make sure the resource is **published** before trying to use its mock API.

If the endpoint does not work:

1. Check that the project exists.
2. Check that the resource exists.
3. Check that the resource is published.
4. Check that you copied the correct API URL.
5. Try opening the URL directly in your browser.

## What's next?

You can now use Mokvio as the API for your frontend during development.

Continue with **API Reference** if you want to learn more about the available API endpoints.
`;

function ConnectMokvio() {
  return (
    <DocLayout>
      <div className="mx-auto w-full max-w-4xl px-6 py-10">
        <MarkdownRenderer>{content}</MarkdownRenderer>
        <DocsPagination />
      </div>
    </DocLayout>
  );
}

export default ConnectMokvio;
