import { Link, useNavigate, useParams } from "react-router-dom";
import { ArrowLeft, Database, Plus } from "lucide-react";

import AppLayout from "@/components/layout/app-layout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";

import ResourceFieldsTable from "@/features/resources/components/ResourceFieldsTable";
import ResourceRuntime from "@/features/resources/components/ResourceRuntime";
import { mockResources } from "@/features/resources/data/resourceMock";

export default function ResourceDetailPage() {
  const { projectSlug, resourceSlug } = useParams();
  const navigate = useNavigate();

  const resource = mockResources.find(
    (item) => item.project_slug === projectSlug && item.slug === resourceSlug,
  );

  if (!resource) {
    return (
      <AppLayout>
        <main className="h-[calc(100vh-6rem)] overflow-auto">
          <div className="mx-auto w-full max-w-5xl px-4 py-6 sm:px-6 sm:py-8">
            <Button variant="outline" size="sm" asChild>
              <Link to={`/project/${projectSlug}`} className="inline-flex items-center gap-2">
                <ArrowLeft className="size-4" />
                <span>Back to Project</span>
              </Link>
            </Button>

            <Card className="mt-6">
              <CardHeader>
                <CardTitle>Resource not found</CardTitle>

                <CardDescription>The requested resource does not exist.</CardDescription>
              </CardHeader>
            </Card>
          </div>
        </main>
      </AppLayout>
    );
  }

  const handleCreateField = () => {
    navigate(`/project/${projectSlug}/resources/${resource.slug}/fields/create`);
  };

  const handleEditField = (field) => {
    navigate(`/project/${projectSlug}/resources/${resource.slug}/fields/${field.slug}/edit`);
  };

  const handleDeleteField = (field) => {
    // eslint-disable-next-line no-console
    console.log("Delete field:", field);
  };

  return (
    <AppLayout>
      <main className="h-[calc(100vh-6rem)] overflow-auto">
        <div className="mx-auto w-full max-w-6xl px-4 py-6 sm:px-6 sm:py-8 lg:px-8">
          <div className="mb-6">
            <Button variant="outline" size="sm" asChild>
              <Link to={`/project/${projectSlug}`} className="inline-flex items-center gap-2">
                <ArrowLeft className="size-4" />
                <span>Back to Project</span>
              </Link>
            </Button>
          </div>

          <div className="mb-8 flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
            <div className="flex items-start gap-3">
              <div className="flex size-11 shrink-0 items-center justify-center rounded-lg border bg-muted/40">
                <Database className="size-5 text-muted-foreground" />
              </div>

              <div className="min-w-0">
                <div className="flex flex-wrap items-center gap-2">
                  <h1 className="text-2xl font-bold tracking-tight sm:text-3xl">{resource.name}</h1>

                  <Badge variant={resource.is_published ? "default" : "secondary"}>
                    {resource.is_published ? "Published" : "Draft"}
                  </Badge>
                </div>

                <p className="mt-1 font-mono text-sm text-muted-foreground">/{resource.slug}</p>

                <p className="mt-2 text-sm text-muted-foreground">
                  Resource in <span className="font-medium text-foreground">{projectSlug}</span>
                </p>
              </div>
            </div>

            <Button onClick={handleCreateField}>
              <Plus className="mr-2 size-4" />
              Create Field
            </Button>
          </div>

          <div className="grid gap-6 lg:grid-cols-[1fr_360px]">
            <Card>
              <CardHeader>
                <CardTitle>Fields</CardTitle>

                <CardDescription>Define the data generated by this resource.</CardDescription>
              </CardHeader>

              <CardContent className="p-0">
                <ResourceFieldsTable
                  fields={resource.fields}
                  onEdit={handleEditField}
                  onDelete={handleDeleteField}
                />
              </CardContent>
            </Card>

            <ResourceRuntime projectSlug={projectSlug} resource={resource} />
          </div>
        </div>
      </main>
    </AppLayout>
  );
}
