# Generated by Django 6.1 on 2026-08-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fields",
            name="generator_options",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
